MS-36 MacOS - Create product list view
LunaBryan/moon-store pull request #16
Opened 2024-12-15 02:59 UTC by DianaZeledon

### **Description**
> Created product list view
> Created search view component

![Screenshot 2024-12-14 at 8 55 17 PM](https://github.com/user-attachments/assets/788b2c12-2a47-43c2-8bb6-af0a188646fb)

---

### **Type of Change**

- [ ] Bug fix
- [X] New feature
- [ ] Repository settings
- [ ] Documentation updated

---

### **Related Issues**
>
> [MS-36](https://developer-solutions.atlassian.net/browse/MS-36)

2024-12-15 18:47 UTC, Rexmoon requested changes
Hey @DianaZeledon,

I noticed some issues comparing with figma design:

- Product's columns is not aligment
- Product's picture is in the same column as product name
- Product's name allows more than 1 line
- Category's badge has black text color
- Category's green badge is darker as figma
- Edit and delete icons don't match
- Text fonts don't match
- Pagination row is missed (Mocked)

Take a look please.

<img width="597" alt="Screenshot 2024-12-15 at 12 36 45" src="https://github.com/user-attachments/assets/ec6272a4-c50f-4ba6-b468-0b30dc0ac1b8" />

2024-12-17 03:05 UTC, DianaZeledon commented
> Hey @DianaZeledon,
> 
> I noticed some issues comparing with figma design:
> 
> * Row should has background color (White and dark as figma)
> * Product's columns is not aligment
> * Product's picture is in the same column as product name
> * Product's name allows more than 1 line
> * Category's badge has black text color
> * Category's green badge is darker as figma
> * Edit and delete icons don't match
> * Text fonts don't match
> * Pagination row is missed (Mocked)
> 
> Take a look please.
> 
> <img alt="Screenshot 2024-12-15 at 12 36 45" width="597" src="https://private-user-images.githubusercontent.com/111804230/395885102-ec6272a4-c50f-4ba6-b468-0b30dc0ac1b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDQ5MzksIm5iZiI6MTczNDQwNDYzOSwicGF0aCI6Ii8xMTE4MDQyMzAvMzk1ODg1MTAyLWVjNjI3MmE0LWM1MGYtNGJhNi1iNDY4LTBiMzBkYzBhYzFiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QwMzAzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDA1NjU2YmM1NjJlOTE2MDU0YTJhMDM5MjNjYzNhYjFiZjcyMTIxMDhmMDkyNmE2M2UzYWRkODg1ZWJmMTAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DWGiPLhuZdoEEwWTsaxuEVW6B24d8wGl6wvN4Vximo8">

I have tried to replicate as much as I can, let me know if more changes are needed.
![image](https://github.com/user-attachments/assets/9260e60e-e9f5-4134-a581-9eb818e91937)

2024-12-17 04:22 UTC, Rexmoon commented on moon-store-mac-os/moon-store-mac-os/Helpers/Components/SearchView.swift
> +        .frame(width: Constants.searchWidht)
```suggestion
        .frame(width: Constants.searchWidth)
```

2024-12-17 04:23 UTC, Rexmoon commented on moon-store-mac-os/moon-store-mac-os/Views/Product/ProductListView.swift
> +            case .productIcon: ""
```suggestion
            case .options, .productIcon: ""
```

2024-12-17 04:24 UTC, Rexmoon commented on moon-store-mac-os/moon-store-mac-os/Views/Product/ProductListView.swift
> +                }
You could use 
```
.background(.msPrimary, in: ....)
```

2024-12-17 04:26 UTC, Rexmoon commented on moon-store-mac-os/moon-store-mac-os/Views/Product/ProductMockData.swift
> +        case .otros: return .gray
You could use implicit return.
```suggestion
        case .frutas: .green
        case .lacteos: .blue
        case .panaderia: .orange
        case .verduras: .red
        case .otros: .gray
```

2024-12-17 04:27 UTC, Rexmoon commented on moon-store-mac-os/moon-store-mac-os/Views/Product/ProductMockData.swift
> +    // Color asociado a cada categoría
Code documentation in English please.

2024-12-17 04:27 UTC, Rexmoon commented on moon-store-mac-os/moon-store-mac-os/Views/Product/ProductMockData.swift
> +
Add MARK

2024-12-17 04:27 UTC, Rexmoon requested changes
Little comments please take a look. Thanks

2024-12-18 02:42 UTC, Rexmoon approved these changes
Amazing!

@DianaZeledon please merge 👍

2024-12-18 02:44 UTC, merged