Create users list view
LunaBryan/moon-store pull request #22
Opened 2024-12-29 02:19 UTC by DianaZeledon

### **Description**
> Created user list view
> Created mock use data
> Created alert to invite user

https://github.com/user-attachments/assets/443338cf-c62f-488d-a758-54df1e43c3d5

---

### **Type of Change**

- [ ] Bug fix
- [X] New feature
- [ ] Repository settings
- [ ] Documentation updated

---

### **Related Issues**
>
> [MS-35](https://developer-solutions.atlassian.net/browse/MS-35)

2024-12-29 02:26 UTC, santelizvargas commented on moon-store-mac-os/moon-store-mac-os/Helpers/Components/HeaderView.swift
> +    private var title: String
Use let

2024-12-29 04:06 UTC, Rexmoon commented on moon-store-mac-os/moon-store-mac-os/Views/User/UserListView.swift
> +                .foregroundStyle(.black)
Use `.msColor`

2024-12-29 18:11 UTC, DerianCordobaPerez commented on moon-store-mac-os/moon-store-mac-os/Views/User/UserListView.swift
> +                            productRowView(
Esto deberia ser renombrado por `userRowView`

```suggestion
                            userRowView(
```

2024-12-29 18:11 UTC, DerianCordobaPerez commented on moon-store-mac-os/moon-store-mac-os/Views/User/UserListView.swift
> +    private func productRowView(userName: String, email: String, role: String, date: String) -> some View {
```suggestion
    private func userRowView(userName: String, email: String, role: String, date: String) -> some View {
```

2024-12-29 18:11 UTC, DerianCordobaPerez commented on moon-store-mac-os/moon-store-mac-os/Views/User/UserListView.swift
> +    // MARK: - Product options view
```suggestion
    // MARK: - User options view
```

2024-12-29 18:11 UTC, DerianCordobaPerez commented on moon-store-mac-os/moon-store-mac-os/Views/User/UserListView.swift
> +    private var opctionsView: some View {
```suggestion
    private var optionsView: some View {
```

2024-12-29 18:12 UTC, DerianCordobaPerez commented on moon-store-mac-os/moon-store-mac-os/Views/User/UserListView.swift
> +    private func productRowView(userName: String, email: String, role: String, date: String) -> some View {
@DianaZeledon También pienso que deberias de pasar la instancia del usuario completa, no le veo sentido estar pasando muchas parametros en un metodo, si deseas mostrar mas campos del usuario, se deberan de agregar mas parametros, si usas la instancia completa, evitas eso.

2024-12-29 18:17 UTC, santelizvargas commented on moon-store-mac-os/moon-store-mac-os/Views/User/UserInviteView.swift
> +                .frame(height: Constants.textFieldHeight)
I think that this VStack is unnecessary

2024-12-29 18:40 UTC, santelizvargas commented on moon-store-mac-os/moon-store-mac-os/Views/User/UserInviteView.swift
> +                }
use simple button here
```suggestion
                Button(Constants.buttonTitle) {
                    isShowing.toggle()
                }
            
```

2024-12-29 18:42 UTC, santelizvargas commented on moon-store-mac-os/moon-store-mac-os/Views/User/UserListView.swift
> +    static let userTitle: String = "Usuarios agregados"
Podemos separar esto en funciones como las que usamos en gallup, para no tenerlo como constante si no como texto

2024-12-29 18:43 UTC, santelizvargas commented on moon-store-mac-os/moon-store-mac-os/Views/User/UserListView.swift
> +enum UserTableHeader: CaseIterable {
este archivo esta muy grande, por favor saque las constantes y los modelos como los enum en archivos aparte

2024-12-29 18:43 UTC, santelizvargas commented on moon-store-mac-os/moon-store-mac-os/Views/User/UserListView.swift
> +    @State private var showActionSheet: Bool = false
Seria show modal

2024-12-29 18:44 UTC, santelizvargas commented on moon-store-mac-os/moon-store-mac-os/Views/User/UserListView.swift
> +                }
hay un boton que ya permite agregar una imagen y un texto, revise please

2024-12-29 18:46 UTC, Rexmoon commented on moon-store-mac-os/moon-store-mac-os/Views/User/UserListView.swift
> +    static let userTitle: String = "Usuarios agregados"
Algo como localized string?

2024-12-29 18:46 UTC, santelizvargas commented on moon-store-mac-os/moon-store-mac-os/Views/User/UserListView.swift
> +        .sheet(isPresented: $showActionSheet) {
Creo que si estamos usando una version mas nueva podemos usar un popover si le sale mejor

2024-12-29 18:48 UTC, santelizvargas commented on moon-store-mac-os/moon-store-mac-os/Views/User/UserListView.swift
> +                    ForEach(Array(UserModel.userMockData.enumerated()), id: \.element.id) { index, user in
no veo donde utiliza el inddice

2024-12-29 18:49 UTC, santelizvargas commented on moon-store-mac-os/moon-store-mac-os/Views/User/UserListView.swift
> +        .clipShape(RoundedRectangle(cornerRadius: Constants.cornerRadius))
```suggestion
        .clipShape(.react(cornerRadius: Constants.cornerRadius))
```

2024-12-29 18:49 UTC, santelizvargas commented on moon-store-mac-os/moon-store-mac-os/Views/User/UserListView.swift
> +                ForEach(UserTableHeader.allCases, id: \.self) { title in
agregue id al enum mejor

2024-12-29 18:49 UTC, santelizvargas commented on moon-store-mac-os/moon-store-mac-os/Views/User/UserListView.swift
> +                        .bold()
```suggestion
                        .font(.body.bold())
```

2024-12-29 18:50 UTC, santelizvargas commented on moon-store-mac-os/moon-store-mac-os/Views/User/UserListView.swift
> +                    .frame(alignment: .center)
remover

2024-12-30 20:15 UTC, DianaZeledon commented on moon-store-mac-os/moon-store-mac-os/Views/User/UserListView.swift
> +                }
@santelizvargas hay un `PrimaryButton` pero el solo revise un texto no un texto y una imagen

2024-12-30 20:17 UTC, DianaZeledon commented on moon-store-mac-os/moon-store-mac-os/Views/User/UserListView.swift
> +        .sheet(isPresented: $showActionSheet) {
Si se hace con un `popover` lo muestra asi
<img width="977" alt="image" src="https://github.com/user-attachments/assets/f49e24be-7f41-4108-8710-0e83f1247695" />

2024-12-30 20:18 UTC, DianaZeledon commented on moon-store-mac-os/moon-store-mac-os/Views/User/UserListView.swift
> +                    ForEach(Array(UserModel.userMockData.enumerated()), id: \.element.id) { index, user in
Se utiliza para dar el color de fondo, ya que el color varia según la fila

2025-01-02 20:48 UTC, DerianCordobaPerez approved these changes

2025-01-02 20:52 UTC, Rexmoon requested changes

2025-01-02 20:52 UTC, Rexmoon commented on moon-store-mac-os/moon-store-mac-os/Views/User/UserInviteView.swift
> +    static let verticalpadding: CGFloat = 5
```
verticalPadding
```

2025-01-02 20:52 UTC, Rexmoon commented on moon-store-mac-os/moon-store-mac-os/Views/User/UserInviteView.swift
> +                    .frame(width: Constants.iconSize,
User frame(square...

2025-01-02 20:52 UTC, Rexmoon commented on moon-store-mac-os/moon-store-mac-os/Views/User/UserInviteView.swift
> +                .frame(maxWidth: .infinity,
````suggestion
.leadingInfinity()
````

2025-01-02 20:52 UTC, Rexmoon commented on moon-store-mac-os/moon-store-mac-os/Views/User/UserInviteView.swift
> +                .clipShape(RoundedRectangle(cornerRadius: Constants.cornerRadius))
```suggestion
.background(.msWhite, in: .reac...
```

2025-01-02 20:52 UTC, Rexmoon commented on moon-store-mac-os/moon-store-mac-os/Views/User/UserListView.swift
> +                .foregroundStyle(.msBlack)
```suggestion
.leadingInfinity()
```

2025-01-02 20:52 UTC, Rexmoon commented on moon-store-mac-os/moon-store-mac-os/Views/User/UserListView.swift
> +}
```suggestion
frame(square...
```

2025-01-02 21:35 UTC, Rexmoon approved these changes

2025-01-02 21:36 UTC, merged